### ISSUE TITLE
rtree missing libspatialindex_c library file

### ISSUE THREAD

**Issue by sjsrey** [pysal/spaghetti#294]
**Describe the bug**
rtree dependency causing post install issues.
 
**To Reproduce**
Steps to reproduce the behavior
```
 >> conda create -n pysal2_1_release python=3 pip
 >> conda activate pysal2_1_release
 >> pip install spaghetti-1.3-py3-none-any.whl
 >> python
 >>> import spaghetti

File "/home/serge/anaconda3/envs/pysal2_1_release/lib/python3.7/site-packages/rtree/core.py", line 125, in <module>
    raise OSError("Could not find libspatialindex_c library file")
OSError: Could not find libspatialindex_c library file
```

**Additional context**
This is blocking the pysal 2.1.0 release as the sdist packages are not passing testing.

**System & Versions**
- Platform information:
```python
>>> import os; print(os.name, os.sys.platform);print(os.uname())
>>> import os;print(os.name, os.sys.platform);print(os.uname())
posix linux
posix.uname_result(sysname='Linux', nodename='snuc-nuc', release='4.18.0-25-generic', version='#26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019', machine='x86_64')

```

**Comment by sjsrey** [comment]
Additional information:
```
$ pip install spaghetti
```
will install, but the problem doesn't arise until the user tries to `import spaghetti`

```
$ conda install --channel conda-forge spaghetti
```
Seems to be fine.

**Comment by jGaboardi** [comment]
I can't reproduce this on my macOS.

```
$ conda create -n pysal2_1_release python=3 pip
$ conda activate pysal2_1_release
$ pip install spaghetti-1.3-py3-none-any.whl
$ python
```
```python
 >>> import spaghetti
/Users/user/miniconda3/envs/pysal2_1_release/lib/python3.7/site-packages/libpysal/weights/util.py:19: UserWarning: geopandas not available. Some functionality will be disabled.
  warn('geopandas not available. Some functionality will be disabled.')
/Users/user/miniconda3/envs/pysal2_1_release/lib/python3.7/site-packages/spaghetti/util.py:13: UserWarning: geopandas/shapely not available. Some functionality will be disabled.
  warn(err_msg)
>>>
>>>
>>> import os; print(os.name, os.sys.platform);print(os.uname())
posix darwin
posix.uname_result(sysname='Darwin', nodename='system.local', release='18.6.0', version='Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64', machine='x86_64')
```

**Comment by jGaboardi** [comment]
Also, this cropped up and was resolved back in May --> #268

**Comment by jGaboardi** [comment]
How would we like to proceed here?

**Comment by jGaboardi** [comment]
pysal/pysal#1123

**Comment by sjsrey** [comment]
I just setup a fresh ubuntu box and am still getting the error when trying to install spaghetti via pip.

I think users have to install libspatialindex separately?

**Comment by jGaboardi** [comment]
> I just setup a fresh ubuntu box and am still getting the error when trying to install spaghetti via pip.

hmmm. This is super frustrating...

> I think users have to install libspatialindex separately?

I don't think so (but I also don't know for sure). May this be an [Ubuntu-specific problem](https://github.com/gboeing/osmnx/issues/45#issuecomment-428297031)?

**Comment by jGaboardi** [comment]
related --> geopandas/geopandas#988

**Comment by sjsrey** [comment]
@jGaboardi if you are installing via pip, rtree requires libspatialindex. https://pypi.org/project/Rtree/

**Comment by weikang9009** [comment]
>  >> conda create -n pysal2_1_release python=3 pip
>  >> conda activate pysal2_1_release
>  >> pip install spaghetti-1.3-py3-none-any.whl
>  >> python
>  >>> import spaghetti

I followed the same steps on my Mac but could not reproduce the error. Importing spaghetti did not throw any error.

Platform info:
```
>>> import os; print(os.name, os.sys.platform);print(os.uname())
posix darwin
posix.uname_result(sysname='Darwin', nodename='weikangs-MBP', release='18.7.0', version='Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64', machine='x86_64')
```

**Comment by sjsrey** [comment]
If you have used conda to install spaghetti before, then libspatialindex is installed and you won't get the error on the pip install - i think.

If I am understanding this correctly, if a user tries to install spaghetti (or the pending pysal-meta) without having first installed libspatialindex (either via conda or their os package manager), then the problem will arise.

**Comment by jGaboardi** [comment]
To Do checklist --> #296

**Comment by jGaboardi** [comment]
Resolved via #298

**Comment by mfschmidt** [comment]
I hope this is useful; sorry about tacking onto a closed issue but it seems likely to help people who land here.

I'm using pipenv in Ubuntu 18.04 and tried to install spaghetti directly in a brand new virgin virtualenv with no other packages installed.

    pipenv install spaghetti

This was successful, no complaints. But when I ran python (3.6.8) and "import spaghetti":

    >>> import spaghetti
    /home/mike/.local/share/virtualenvs/tmp-gPS56xMp/lib/python3.6/site-packages/libpysal/weights/util.py:19: UserWarning: geopandas not available. Some functionality will be disabled.
    warn('geopandas not available. Some functionality will be disabled.')
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/mike/.local/share/virtualenvs/tmp-gPS56xMp/lib/python3.6/site-packages/spaghetti/__init__.py", line 7, in <module>
      from .network import Network, PointPattern, SimulatedPointPattern
    File "/home/mike/.local/share/virtualenvs/tmp-gPS56xMp/lib/python3.6/site-packages/spaghetti/network.py", line 7, in <module>
      from . import util
    File "/home/mike/.local/share/virtualenvs/tmp-gPS56xMp/lib/python3.6/site-packages/spaghetti/util.py", line 5, in <module>
      from rtree import Rtree
    File "/home/mike/.local/share/virtualenvs/tmp-gPS56xMp/lib/python3.6/site-packages/rtree/__init__.py", line 1, in <module>
      from .index import Rtree
    File "/home/mike/.local/share/virtualenvs/tmp-gPS56xMp/lib/python3.6/site-packages/rtree/index.py", line 5, in <module>
      from . import core
    File "/home/mike/.local/share/virtualenvs/tmp-gPS56xMp/lib/python3.6/site-packages/rtree/core.py", line 125, in <module>
      raise OSError("Could not find libspatialindex_c library file")
    OSError: Could not find libspatialindex_c library file

Googling led me to realize that libspatialindex is a system-level package that is not part of the default Ubuntu installation. I installed it with

    sudo apt install libspatialindex-dev

And the error no longer bothered me. I was warned about some disabled functionality due to missing geopandas, but `pipenv install geopandas` resolved that. Everything now seems to work.
